Vsat = (3.23e-4).*(Vds.^2);
Vgt = (6.57e-5).*(Vds.^2);

plot(Vds,[...
        Id0,...
        Id1,...
        Id2,...
        Id3,...
        Id4,...
        Id5,...
        Vsat,...
        Vgt...
        ],'LineWidth',2);
%         divd(Vds,Id0),...
%         divd(Vds,Id1),...
%         divd(Vds,Id2),...
%         divd(Vds,Id3),...
%         divd(Vds,Id4),...
%         divd(Vds,Id5),...
        
%       divd(Vds,divd(Vds,Id0))...
%         divd(Vds,divd(Vds,Id1)),...
%         divd(Vds,divd(Vds,Id2)),...
%         divd(Vds,divd(Vds,Id3)),...
%         divd(Vds,divd(Vds,Id4)),...
%         divd(Vds,divd(Vds,Id5))...
axis([0 5 0 0.0014]);
%text(0.5,0.6,'$$\mathsf{math\,\,mode\,\,sans\,\,serif}$$','Interpreter','LaTex');

%'$$\mathsf{\frac{d^2(I_D)}{d({V_{DS}}^2)} (V_{GS} = 0 V)}$$',...
%     '$$\mathsf{\frac{d^2(I_D)}{d({V_{DS}}^2)} (V_{GS} = 1 V)}$$',...
%     '$$\mathsf{\frac{d^2(I_D)}{d({V_{DS}}^2)} (V_{GS} = 2 V)}$$',...
%     '$$\mathsf{\frac{d^2(I_D)}{d({V_{DS}}^2)} (V_{GS} = 3 V)}$$',...
%     '$$\mathsf{\frac{d^2(I_D)}{d({V_{DS}}^2)} (V_{GS} = 4 V)}$$',...
%     '$$\mathsf{\frac{d^2(I_D)}{d({V_{DS}}^2)} (V_{GS} = 5 V)}$$'...
% '$$\mathsf{\frac{d(I_D)}{d(V_{DS})} (V_{GS} = 0 V)}$$',...
%     '$$\mathsf{\frac{d(I_D)}{d(V_{DS})} (V_{GS} = 1 V)}$$',...
%     '$$\mathsf{\frac{d(I_D)}{d(V_{DS})} (V_{GS} = 2 V)}$$',...
%     '$$\mathsf{\frac{d(I_D)}{d(V_{DS})} (V_{GS} = 3 V)}$$',...
%     '$$\mathsf{\frac{d(I_D)}{d(V_{DS})} (V_{GS} = 4 V)}$$',...
%     '$$\mathsf{\frac{d(I_D)}{d(V_{DS})} (V_{GS} = 5 V)}$$',...


h = legend(... 
        '$$\mathsf{I_D (V_{GS} = 0 V)}$$',...
    '$$\mathsf{I_D (V_{GS} = 1 V)}$$',...
    '$$\mathsf{I_D (V_{GS} = 2 V)}$$',...
    '$$\mathsf{I_D (V_{GS} = 3 V)}$$',...
    '$$\mathsf{I_D (V_{GS} = 4 V)}$$',...
    '$$\mathsf{I_D (V_{GS} = 5 V)}$$',...
    '$$\mathsf{V_{DSAT}}$$',...    
    '$$\mathsf{V_{GT}}$$'...
    );
set(h,'FontSize',12);
xlabel('$$\mathsf{V_{DS}}$$','FontSize',20);
ylabel('$$\mathsf{I_{D}}$$','FontSize',20);