-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 23-Sep-13 11:14:11
-- Path: /home/rphes/DaC/hardware/opdracht3/pwm/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Pwm_gen IS

  SIGNAL n68: STD_LOGIC;
  SIGNAL n67: STD_LOGIC;
  SIGNAL n64: STD_LOGIC;
  SIGNAL n66: STD_LOGIC;
  SIGNAL n62: STD_LOGIC;
  SIGNAL n63: STD_LOGIC;
  SIGNAL N_20: STD_LOGIC;
  SIGNAL n61: STD_LOGIC;
  SIGNAL n57: STD_LOGIC;
  SIGNAL n55: STD_LOGIC;
  SIGNAL n56: STD_LOGIC;
  SIGNAL n58: STD_LOGIC;
  SIGNAL n52: STD_LOGIC;
  SIGNAL n53: STD_LOGIC;
  SIGNAL n54: STD_LOGIC;
  SIGNAL count_3_port: STD_LOGIC;
  SIGNAL n49: STD_LOGIC;
  SIGNAL n50: STD_LOGIC;
  SIGNAL n46: STD_LOGIC;
  SIGNAL n47: STD_LOGIC;
  SIGNAL n60: STD_LOGIC;
  SIGNAL n44: STD_LOGIC;
  SIGNAL n48: STD_LOGIC;
  SIGNAL n45: STD_LOGIC;
  SIGNAL N_26: STD_LOGIC;
  SIGNAL n17_port: STD_LOGIC;
  SIGNAL n51: STD_LOGIC;
  SIGNAL N_19: STD_LOGIC;
  SIGNAL n69: STD_LOGIC;
  SIGNAL n70: STD_LOGIC;
  SIGNAL n65: STD_LOGIC;
  SIGNAL n59: STD_LOGIC;
  SIGNAL count_2_port: STD_LOGIC;
  SIGNAL N_17: STD_LOGIC;
  SIGNAL n73: STD_LOGIC;
  SIGNAL n72: STD_LOGIC;
  SIGNAL n71: STD_LOGIC;
  SIGNAL count_0_port: STD_LOGIC;
  SIGNAL N_18: STD_LOGIC;
  SIGNAL count_1_port: STD_LOGIC;

  SIGNAL pulse_int: STD_LOGIC;

BEGIN

  pulse <= pulse_int;


  U46: iv110 PORT MAP (width(3), n48);
  U64: iv110 PORT MAP (n67, n66);
  U78: iv110 PORT MAP (enabled, n73);
  U75: iv110 PORT MAP (count_0_port, n59);
  U74: iv110 PORT MAP (n72, n17_port);
  U53: iv110 PORT MAP (n56, n53);
  U71: iv110 PORT MAP (n71, n69);
  U52: iv110 PORT MAP (count_2_port, n51);
  U70: iv110 PORT MAP (count_1_port, n70);
  U50: iv110 PORT MAP (n55, n54);
  U66: iv110 PORT MAP (n65, n68);
  U45: na210 PORT MAP (count_3_port, n48, n47);
  U63: na210 PORT MAP (count_3_port, n66, n62);
  U44: na210 PORT MAP (n46, n47, n45);
  U43: na210 PORT MAP (n44, n45, N_26);
  U61: na210 PORT MAP (n62, n63, N_20);
  U59: na210 PORT MAP (count_3_port, n61, n60);
  U58: na210 PORT MAP (width(3), n60, n44);
  U57: na210 PORT MAP (width(0), n59, n58);
  U56: na210 PORT MAP (count_1_port, n58, n52);
  U67: na210 PORT MAP (count_2_port, count_3_port, n64);
  U48: na210 PORT MAP (width(2), n51, n50);
  U47: na210 PORT MAP (n49, n50, n46);
  U62: na310 PORT MAP (count_2_port, n64, n65, n63);
  U60: na310 PORT MAP (width(0), width(2), width(1), n61);
  U49: na310 PORT MAP (n52, n53, n54, n49);
  count_reg_2_inst: dfr11 PORT MAP (N_19, reset, clk, count_2_port);
  count_reg_0_inst: dfr11 PORT MAP (N_17, reset, clk, count_0_port);
  pulse_reg: dfr11 PORT MAP (N_26, n17_port, clk, pulse_int);
  count_reg_3_inst: dfr11 PORT MAP (N_20, reset, clk, count_3_port);
  count_reg_1_inst: dfr11 PORT MAP (N_18, reset, clk, count_1_port);
  U77: no210 PORT MAP (n73, reset, n72);
  U55: no210 PORT MAP (n58, count_1_port, n57);
  U73: no210 PORT MAP (n59, n17_port, n71);
  U54: no210 PORT MAP (n57, width(1), n56);
  U69: no210 PORT MAP (n69, n70, n65);
  U51: no210 PORT MAP (n51, width(2), n55);
  U65: no210 PORT MAP (n64, n68, n67);
  U76: ex210 PORT MAP (count_0_port, n72, N_17);
  U72: ex210 PORT MAP (count_1_port, n71, N_18);
  U68: ex210 PORT MAP (count_2_port, n65, N_19);

END extracted;



