1.000000e-10  ( clk ) ( reset ) ( enable ) ( x_7_0_7 ) ( x_7_0_6 ) ( x_7_0_5 ) ( x_7_0_4 ) ( x_7_0_3 ) ( x_7_0_2 ) ( x_7_0_1 ) ( x_7_0_0 ) ( y_6_0_6 ) ( y_6_0_5 ) ( y_6_0_4 ) ( y_6_0_3 ) ( y_6_0_2 ) ( y_6_0_1 ) ( y_6_0_0 ) ( color_3_0_3 ) ( color_3_0_2 ) ( color_3_0_1 ) ( color_3_0_0 ) ( asb ) ( done ) ( ramaddr_15_0_15 ) ( ramaddr_15_0_14 ) ( ramaddr_15_0_13 ) ( ramaddr_15_0_12 ) ( ramaddr_15_0_11 ) ( ramaddr_15_0_10 ) ( ramaddr_15_0_9 ) ( ramaddr_15_0_8 ) ( ramaddr_15_0_7 ) ( ramaddr_15_0_6 ) ( ramaddr_15_0_5 ) ( ramaddr_15_0_4 ) ( ramaddr_15_0_3 ) ( ramaddr_15_0_2 ) ( ramaddr_15_0_1 ) ( ramaddr_15_0_0 ) ( ramdata_3_0_3 ) ( ramdata_3_0_2 ) ( ramdata_3_0_1 ) ( ramdata_3_0_0 ) ( draw_write ) ( draw_can_access )
              0hhllllllllllllllllhlhhllxxxxxxxxxxxxxxxxxxxxll
              0hhllllllllllllllllhlhhllhhlhlllhhlhhhhhhhhllll
            100lhllllllllllllllllhlhhllhhlhlllhhlhhhhhhhhllll
            200hhllllllllllllllllhlhhllhhlhlllhhlhhhhhhhhllll
            300lhllllllllllllllllhlhhllhhlhlllhhlhhhhhhhhllll
            400hlllllllllllllllllhlhhllhhlhlllhhlhhhhhhhhlllh
            500llllllllllllllllllhlhhllhhlhlllhhlhhhhhhhhlllh
            600hlhhlhlhlhlhlhlhhhhlhhllhhlhlllhhlhhhhhhhhlllh
            601hlhhlhlhlhlhlhlhhhhlhhllhxlxlxxxxlxhxhxhhhlllh
            647hlhhlhlhlhlhlhlhhhhlhhllhhlhlhhhhlxhxhxhhhlllh
            674hlhhlhlhlhlhlhlhhhhlhhllhhlhlhhhhlhlhlhlhlhhhh
            700llhhlhlhlhlhlhlhhhhlhhllhhlhlhhhhlhlhlhlhlhhhh
            800hlhhlhlhlhlhlhlhhhhlhhllhhlhlhhhhlhlhlhlhlhhhh
            815hlhhlhlhlhlhlhlhhhhlhhlhhhlhlhhhhlhlhlhlhlhhhh
            838hlhhlhlhlhlhlhlhhhhlhhlhhhlhlhhhhlhlhlhlhlhhlh
            900llhhlhlhlhlhlhlhhhhlhhlhhhlhlhhhhlhlhlhlhlhhlh
           1000hllhlhlhlhlhlhlhhhhlhhlhhhlhlhhhhlhlhlhlhlhhlh
           1002hllhlhlhlhlhlhlhhhhlhhllhhlhlhhhhlhlhlhlhlhhlh
           1100lllhlhlhlhlhlhlhhhhlhhllhhlhlhhhhlhlhlhlhlhhlh
           1200hlhhhhllhhhhhhhlllhlhhllhhlhlhhhhlhlhlhlhlhhlh
           1201hlhhhhllhhhhhhhlllhlhhllhhxhxxxxhxhlxxhxhlhhlh
           1247hlhhhhllhhhhhhhlllhlhhllhhhhhlllhxhlxxhxhlhhlh
           1274hlhhhhllhhhhhhhlllhlhhllhhhhhlllhhhllhhhhlhhhh
           1300llhhhhllhhhhhhhlllhlhhllhhhhhlllhhhllhhhhlhhhh
           1400hlhhhhllhhhhhhhlllhlhhllhhhhhlllhhhllhhhhlhhhh
           1415hlhhhhllhhhhhhhlllhlhhlhhhhhhlllhhhllhhhhlhhhh
           1438hlhhhhllhhhhhhhlllhlhhlhhhhhhlllhhhllhhhhlhhlh
           1500llhhhhllhhhhhhhlllhlhhlhhhhhhlllhhhllhhhhlhhlh
           1600hllhhhllhhhhhhhlllhlhhlhhhhhhlllhhhllhhhhlhhlh
           1602hllhhhllhhhhhhhlllhlhhllhhhhhlllhhhllhhhhlhhlh
           1700lllhhhllhhhhhhhlllhlhhllhhhhhlllhhhllhhhhlhhlh
           1800hllhhhllhhhhhhhlllhlhhllhhhhhlllhhhllhhhhlhhlh
           1900lllhhhllhhhhhhhlllhlhhllhhhhhlllhhhllhhhhlhhlh
           1999lllhhhllhhhhhhhlllhlhhllhhhhhlllhhhllhhhhlhhlh
