-- Generated by: xvhdl 2.49 31-Jul-2008
-- Date: 26-Sep-13 8:58:07
-- Path: /home/rphes/DaC/hardware/opdracht3/pwm_gen/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Pwm_gen IS

  SIGNAL n61: STD_LOGIC;
  SIGNAL N_17: STD_LOGIC;
  SIGNAL n60: STD_LOGIC;
  SIGNAL n58: STD_LOGIC;
  SIGNAL N_19: STD_LOGIC;
  SIGNAL n59: STD_LOGIC;
  SIGNAL N_18: STD_LOGIC;
  SIGNAL count_1_port: STD_LOGIC;
  SIGNAL count_2_port: STD_LOGIC;
  SIGNAL n49: STD_LOGIC;
  SIGNAL n50: STD_LOGIC;
  SIGNAL n47: STD_LOGIC;
  SIGNAL n51: STD_LOGIC;
  SIGNAL n45: STD_LOGIC;
  SIGNAL n46: STD_LOGIC;
  SIGNAL n41: STD_LOGIC;
  SIGNAL n42: STD_LOGIC;
  SIGNAL count_3_port: STD_LOGIC;
  SIGNAL n56: STD_LOGIC;
  SIGNAL n39: STD_LOGIC;
  SIGNAL n40: STD_LOGIC;
  SIGNAL n57: STD_LOGIC;
  SIGNAL n54: STD_LOGIC;
  SIGNAL n53: STD_LOGIC;
  SIGNAL n48: STD_LOGIC;
  SIGNAL n52: STD_LOGIC;
  SIGNAL n44: STD_LOGIC;
  SIGNAL n43: STD_LOGIC;
  SIGNAL N_25: STD_LOGIC;
  SIGNAL N_26: STD_LOGIC;
  SIGNAL n38: STD_LOGIC;
  SIGNAL n55: STD_LOGIC;
  SIGNAL N_16: STD_LOGIC;
  SIGNAL count_0_port: STD_LOGIC;

  SIGNAL pulse_int: STD_LOGIC;

BEGIN

  pulse <= pulse_int;


  U46: na310 PORT MAP (n49, n50, n51, n45);
  U56: na310 PORT MAP (width(0), width(2), width(1), n57);
  U64: iv110 PORT MAP (reset, n38);
  U44: iv110 PORT MAP (n47, n46);
  U59: iv110 PORT MAP (count_3_port, n44);
  U41: iv110 PORT MAP (n43, n42);
  U49: iv110 PORT MAP (n52, n50);
  U67: iv110 PORT MAP (count_0_port, n55);
  U48: iv110 PORT MAP (width(2), n48);
  U65: iv110 PORT MAP (count_1_port, n61);
  U45: no210 PORT MAP (n48, count_2_port, n47);
  U61: no210 PORT MAP (n60, n61, n59);
  U42: no210 PORT MAP (n44, width(3), n43);
  U51: no210 PORT MAP (n54, count_1_port, n53);
  U50: no210 PORT MAP (n53, width(1), n52);
  U63: na210 PORT MAP (count_0_port, n38, n60);
  U43: na210 PORT MAP (n45, n46, n41);
  U58: na210 PORT MAP (n59, count_2_port, n58);
  U40: na210 PORT MAP (n41, n42, n40);
  U39: na210 PORT MAP (n39, n40, N_25);
  U38: na210 PORT MAP (enabled, n38, N_26);
  U55: na210 PORT MAP (count_3_port, n57, n56);
  U54: na210 PORT MAP (width(3), n56, n39);
  U53: na210 PORT MAP (width(0), n55, n54);
  U52: na210 PORT MAP (count_1_port, n54, n49);
  U47: na210 PORT MAP (count_2_port, n48, n51);
  U62: ex210 PORT MAP (n61, n60, N_17);
  U60: ex210 PORT MAP (count_2_port, n59, N_18);
  U57: ex210 PORT MAP (n44, n58, N_19);
  U66: ex210 PORT MAP (n55, reset, N_16);
  count_reg_2_inst: dfr11 PORT MAP (N_18, reset, clk, count_2_port);
  count_reg_0_inst: dfr11 PORT MAP (N_16, reset, clk, count_0_port);
  pulse_reg: dfr11 PORT MAP (N_25, N_26, clk, pulse_int);
  count_reg_3_inst: dfr11 PORT MAP (N_19, reset, clk, count_3_port);
  count_reg_1_inst: dfr11 PORT MAP (N_17, reset, clk, count_1_port);

END extracted;



